tare_planner_node:
  ros__parameters:
    sub_start_exploration_topic_ : /start_exploration
    sub_terrain_map_topic_ : /terrain_map
    sub_terrain_map_ext_topic_ : /terrain_map_ext
    sub_state_estimation_topic_ : /state_estimation_at_scan
    sub_registered_scan_topic_ : /registered_scan
    sub_coverage_boundary_topic_ : /sensor_coverage_planner/coverage_boundary
    sub_viewpoint_boundary_topic_ : /navigation_boundary
    sub_nogo_boundary_topic_ : /sensor_coverage_planner/nogo_boundary
    sub_joystick_topic_ : /joy
    sub_reset_waypoint_topic_ : /reset_waypoint
    pub_exploration_finish_topic_ : exploration_finish
    pub_runtime_breakdown_topic_ : runtime_breakdown
    pub_runtime_topic_ : /runtime
    pub_waypoint_topic_ : /way_point
    pub_momentum_activation_count_topic_ : momentum_activation_count

    kAutoStart : true
    kRushHome : true
    kUseTerrainHeight : false
    kCheckTerrainCollision : true
    kExtendWayPoint : true                      # 原值true
    kUseLineOfSightLookAheadPoint : true
    kNoExplorationReturnHome : true
    kExtendWayPointDistanceBig : 2.0             # 原值8.0 超过雷达距离一点
    kExtendWayPointDistanceSmall : 1.5            # 原值3.5 和雷达距离一致
    kKeyposeCloudDwzFilterLeafSize : 0.2
    kRushHomeDist : 5.0
    kAtHomeDistThreshold : 0.5
    kTerrainCollisionThreshold : 0.5             # 原值0.5,intensity超过这个值的点，将不被viewpoint选中
    kLookAheadDistance : 8.0
    kUseMomentum : false 
    kDirectionChangeCounterThr : 6
    kDirectionNoChangeCounterThr : 5
    kResetWaypointJoystickAxesID : 2

    # PlanningEnv
    kUseFrontier : true
    kFrontierClusterTolerance : 1.0
    kFrontierClusterMinSize : 10                # 原值10
    kUseCoverageBoundaryOnFrontier : false 
    kUseCoverageBoundaryOnObjectSurface : false

    # Rolling occupancy grid
    rolling_occupancy_grid/resolution_x : 0.3
    rolling_occupancy_grid/resolution_y : 0.3
    rolling_occupancy_grid/resolution_z : 0.3

    kSurfaceCloudDwzLeafSize : 0.3
    kCollisionCloudDwzLeafSize : 0.1          # 碰撞坚持点云分辨率 原值0.2   0.1
    kKeyposeCloudStackNum : 5
    kPointCloudRowNum : 50
    kPointCloudColNum : 50
    kPointCloudLevelNum : 30
    kMaxCellPointNum : 100000
    kPointCloudCellSize : 18.0
    kPointCloudCellHeight : 1.8
    kPointCloudManagerNeighborCellNum : 5
    kCoverCloudZSqueezeRatio : 2.0

    # KeyposeGraph
    keypose_graph/kAddNodeMinDist : 1.0
    keypose_graph/kAddNonKeyposeNodeMinDist : 0.5
    keypose_graph/kAddEdgeConnectDistThr : 3.0
    keypose_graph/kAddEdgeToLastKeyposeDistThr : 3.0
    keypose_graph/kAddEdgeVerticalThreshold : 1.0
    keypose_graph/kAddEdgeCollisionCheckResolution : 0.4
    keypose_graph/kAddEdgeCollisionCheckRadius : 0.4
    keypose_graph/kAddEdgeCollisionCheckPointNumThr : 1

    # ViewPointManager
    viewpoint_manager/number_x : 200                # 原值50，大一点，让边界点都落在绿色框范围内
    viewpoint_manager/number_y : 200
    viewpoint_manager/number_z : 1
    viewpoint_manager/resolution_x : 0.15         # 分辨率 原值0.4,值越大 horizen绿框边长越大
    viewpoint_manager/resolution_y : 0.15
    viewpoint_manager/resolution_z : 0.0
    kConnectivityHeightDiffThr : 0.25
    kGreedyViewPointSampleRange : 3
    kLocalPathOptimizationItrMax : 10
    # kViewPointCollisionMargin 的2倍要大于 viewpoint_manager/resolution_x 不然waypoint穿墙
    kViewPointCollisionMargin : 0.1                # 视点碰撞检查边距 原值 0.6 如果这个范围内有障碍物，说明当前viewpoint有碰撞风险，不可选 0.15
    kViewPointCollisionMarginZPlus : 0.5
    kViewPointCollisionMarginZMinus : 0.5
    kCollisionGridZScale : 1.0
    kCollisionGridResolutionX : 0.2
    kCollisionGridResolutionY : 0.2
    kCollisionGridResolutionZ : 0.0
    kCollisionPointThr : 1
    kLineOfSightStopAtNearestObstacle : true
    kViewPointHeightFromTerrain : 0.75
    kViewPointHeightFromTerrainChangeThreshold : 0.6
    kCheckDynamicObstacleCollision : false
    kCollisionFrameCountMax : 3

    kSensorRange : 3.5                # 激光点云覆盖的举例,原值3.5
    kNeighborRange : 1.0                # 默认值 3.0  这个决定小方块大小
    kCoverageOcclusionThr : 0.3         # 原址0.3 用于在视点管理和可见性计算中处理遮挡情况，确保算法能够更准确地判断哪些点是可见的
    kCoverageDilationRadius : 0.5

    # Grid World
    kGridWorldXNum : 121
    kGridWorldYNum : 121
    kGridWorldZNum : 121
    kGridWorldCellHeight : 3.0
    kGridWorldNearbyGridNum : 5
    kMinAddPointNumSmall : 3            # 视点最小覆盖的点数量 ,原值30，15是测试下来的极限值，不要动了
    kMinAddPointNumBig : 50
    kMinAddFrontierPointNum : 1         # 视点最小覆盖的前沿点数量,原值10，5是测试下来的极限值，不要动了
    kCellExploringToCoveredThr : 1
    kCellCoveredToExploringThr: 10
    kCellExploringToAlmostCoveredThr: 10
    kCellAlmostCoveredToExploringThr: 20
    kCellUnknownToExploringThr: 1

    # Visualization
    kExploringSubspaceMarkerColorGradientAlpha : true
    kExploringSubspaceMarkerColorMaxAlpha : 0.8
    kExploringSubspaceMarkerColorR : 0.0
    kExploringSubspaceMarkerColorG : 1.0
    kExploringSubspaceMarkerColorB : 0.0
    kExploringSubspaceMarkerColorA : 1.0
    kLocalPlanningHorizonMarkerColorR : 0.0
    kLocalPlanningHorizonMarkerColorG : 1.0
    kLocalPlanningHorizonMarkerColorB : 0.0
    kLocalPlanningHorizonMarkerColorA : 1.0
    kLocalPlanningHorizonMarkerWidth : 0.3
    kLocalPlanningHorizonHeight : 3.0
